In [2]:
import pandas as pd

#### There are two keys data structure in the pandas library 
#### series(1 Dimenstial)
#### DataFrame(2 Dimenstial)

In [4]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
df=pd.DataFrame({"names":["vishal","nishant","rohan","subham"],"marks":[100,53,78,90]})

In [6]:
df

     names  marks
0   vishal    100
1  nishant     53
2    rohan     78
3   subham     90

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   4 non-null      object
 1   marks   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [8]:
df.describe()

           marks
count    4.00000
mean    80.25000
std     20.27108
min     53.00000
25%     71.75000
50%     84.00000
75%     92.50000
max    100.00000

In [9]:
df.tail()

     names  marks
0   vishal    100
1  nishant     53
2    rohan     78
3   subham     90

In [10]:
#data slection

In [11]:
type(df["names"])

pandas.core.series.Series

In [12]:
df

     names  marks
0   vishal    100
1  nishant     53
2    rohan     78
3   subham     90

In [13]:
df.iloc[0]

names    vishal
marks       100
Name: 0, dtype: object

In [14]:
type(df["names"])

pandas.core.series.Series

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   4 non-null      object
 1   marks   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [16]:
df['names']=df['names'].astype('category')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   4 non-null      category
 1   marks   4 non-null      int64
dtypes: category(1), int64(1)
memory usage: 372.0 bytes

In [18]:
df["names"][0]

'vishal'

In [19]:
type(df["names"])

pandas.core.series.Series

In [20]:
print(df["names"].cat.categories)

Index(['nishant', 'rohan', 'subham', 'vishal'], dtype='object')

In [21]:
print(pd.__version__)

2.3.1

In [22]:
len(df)

4

In [23]:
df["zero"]=[0 for i in range(len(df))]

In [24]:
df

     names  marks  zero
0   vishal    100     0
1  nishant     53     0
2    rohan     78     0
3   subham     90     0

In [25]:
def fx(a):
    return a+1
df["zero+1"]=df["zero"].apply(fx)

In [26]:
df

     names  marks  zero  zero+1
0   vishal    100     0       1
1  nishant     53     0       1
2    rohan     78     0       1
3   subham     90     0       1

In [27]:
df1=pd.DataFrame({"name":["harry","rohan","subham","shivam","divya","aperna","khushi"]
                  ,"marks":[100,53,45,3,100,95,3]})

In [28]:
df1

     name  marks
0   harry    100
1   rohan     53
2  subham     45
3  shivam      3
4   divya    100
5  aperna     95
6  khushi      3

In [29]:
df2=pd.DataFrame({"name":["akash","vishal","rukmani","rahul","abhi","kartik","keshav"]
                  ,"marks":[13,58,44,35,10,96,25]})

In [30]:
df2

      name  marks
0    akash     13
1   vishal     58
2  rukmani     44
3    rahul     35
4     abhi     10
5   kartik     96
6   keshav     25

In [31]:
pd.concat([df1,df2])

      name  marks
0    harry    100
1    rohan     53
2   subham     45
3   shivam      3
4    divya    100
5   aperna     95
6   khushi      3
0    akash     13
1   vishal     58
2  rukmani     44
3    rahul     35
4     abhi     10
5   kartik     96
6   keshav     25

In [32]:
df1=pd.DataFrame({"name":["akash","priyanka"],"marks":[13,58]})

In [33]:
df2=pd.DataFrame({"name":["akash","priyanka"],"roll":[1244,1245]})

In [34]:
pd.merge(df1,df2,on="name")

       name  marks  roll
0     akash     13  1244
1  priyanka     58  1245

In [35]:
pd.merge(df1,df2,on="name",how="outer")

       name  marks  roll
0     akash     13  1244
1  priyanka     58  1245

In [ ]:
!pip install selenium # use for scraping data from website

Collecting selenium
  Downloading selenium-4.40.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from selenium) (2026.1.4)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.32.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting trio-typing>=0.10.0 (from selenium)
  Downloading trio_typing-0.10.0-py3-none-any.whl.metadata (10 kB)
Collecting types-certifi>=2021.10.8.3 (from selenium)
  Downloading types_certifi-2021.10.8.3-py3-none-any.whl.metadata (1.4 kB)
Collecting types-urllib3>=1.26.25.14 (from selenium)
  Downloading types_urllib3-1.26.25.14-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting cffi>=1.14 (from trio<1.0,>=0.31.0->selenium)
  Downloading cffi-2.0.0-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting pycparser (from cffi>=1.14->trio<1.0,>=0.31.0->selenium)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting mypy-extensions>=0.4.2 (from trio-typing>=0.10.0->selenium)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting async-generator (from trio-typing>=0.10.0->selenium)
  Downloading async_generator-1.10-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: packaging in c:\users\hp\appdata\roaming\python\python313\site-packages (from trio-typing>=0.10.0->selenium) (26.0)
Collecting importlib-metadata (from trio-typing>=0.10.0->selenium)
  Downloading importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting h11<1,>=0.16.0 (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting zipp>=3.20 (from importlib-metadata->trio-typing>=0.10.0->selenium)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Downloading selenium-4.40.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.6 MB 2.6 MB/s eta 0:00:04
   ----- ---------------------------------- 1.3/9.6 MB 2.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.6 MB 2.9 MB/s eta 0:00:03
   ------------ --------------------------- 2.9/9.6 MB 3.1 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.6 MB 3.3 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.6 MB 3.6 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.6 MB 3.8 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.6 MB 4.1 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.6 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 4.5 MB/s  0:00:02
Downloading trio-0.32.0-py3-none-any.whl (512 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading cffi-2.0.0-cp313-cp313-win_amd64.whl (183 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading trio_typing-0.10.0-py3-none-any.whl (42 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading types_certifi-2021.10.8.3-py3-none-any.whl (2.1 kB)
Downloading types_urllib3-1.26.25.14-py3-none-any.whl (15 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Downloading importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: types-urllib3, types-certifi, sortedcontainers, zipp, websocket-client, sniffio, pysocks, pycparser, mypy-extensions, h11, attrs, async-generator, wsproto, outcome, importlib-metadata, cffi, trio, trio-websocket, trio-typing, selenium

   ---- -----------------------------------  2/20 [sortedcontainers]
   -------- -------------------------------  4/20 [websocket-client]
   -------- -------------------------------  4/20 [websocket-client]
   -------- -------------------------------  4/20 [websocket-client]
   ---------- -----------------------------  5/20 [sniffio]
   -------------- -------------------------  7/20 [pycparser]
   ------------------ ---------------------  9/20 [h11]
   -------------------- ------------------- 10/20 [attrs]
   -------------------- ------------------- 10/20 [attrs]
   ---------------------- ----------------- 11/20 [async-generator]
   ------------------------ --------------- 12/20 [wsproto]
   -------------------------- ------------- 13/20 [outcome]
   ---------------------------- ----------- 14/20 [importlib-metadata]
   ------------------------------ --------- 15/20 [cffi]
   ------------------------------ --------- 15/20 [cffi]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   -------------------------------- ------- 16/20 [trio]
   ---------------------------------- ----- 17/20 [trio-websocket]
   ------------------------------------ --- 18/20 [trio-typing]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   -------------------------------------- - 19/20 [selenium]
   ---------------------------------------- 20/20 [selenium]

Successfully installed async-generator-1.10 attrs-25.4.0 cffi-2.0.0 h11-0.16.0 importlib-metadata-8.7.1 mypy-extensions-1.1.0 outcome-1.3.0.post0 pycparser-3.0 pysocks-1.7.1 selenium-4.40.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.32.0 trio-typing-0.10.0 trio-websocket-0.12.2 types-certifi-2021.10.8.3 types-urllib3-1.26.25.14 websocket-client-1.9.0 wsproto-1.3.2 zipp-3.23.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
!pip install webdriver-manager # use for managing the web driver for selenium, it automatically downloads and sets up the web driver for you, so you don't have to manually download and configure it.

Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from webdriver-manager) (2.32.5)
Collecting python-dotenv (from webdriver-manager)
  Downloading python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: packaging in c:\users\hp\appdata\roaming\python\python313\site-packages (from webdriver-manager) (26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->webdriver-manager) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->webdriver-manager) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->webdriver-manager) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->webdriver-manager) (2026.1.4)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Downloading python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Installing collected packages: python-dotenv, webdriver-manager

   -------------------- ------------------- 1/2 [webdriver-manager]
   -------------------- ------------------- 1/2 [webdriver-manager]
   ---------------------------------------- 2/2 [webdriver-manager]

Successfully installed python-dotenv-1.2.1 webdriver-manager-4.0.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
#start browser
driver=webdriver.Chrome(service=Service(ChromeDriverManager().install()))

<div style="text-align: center; padding: 20px;">
    <h1>Alex Johnson</h1>
    <h2>Exploratory Data Analysis on Sales Data</h2>
    <p style="font-size: 16px; max-width: 700px; margin: auto;">
        This notebook explores historical sales data to uncover trends, patterns,
        and actionable insights using Python and data visualization techniques.
    </p>
    <hr style="width: 60%;">
</div>