In [105]:
import pandas as pd

In [2]:
pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6],
})

   A  B
0  1  4
1  2  5
2  3  6

In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [4]:
url="https://www.flipkart.com/tyy/4io/~cs-yyz0z07a06/pr?sid=tyy%2C4io&collection-tab-name=samsung+S24+5G+SD&pageCriteria=default&param=3838&hpid=H3kVFvfATcBjl0FYDg15tqp7_Hsxr70nj65vMAAFKlc%3D&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InZhbHVlQ2FsbG91dCI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ2YWx1ZUNhbGxvdXQiLCJpbmZlcmVuY2VUeXBlIjoiVkFMVUVfQ0FMTE9VVCIsInZhbHVlcyI6WyJGcm9tIOKCuTQwLDk5OSJdLCJ2YWx1ZVR5cGUiOiJNVUxUSV9WQUxVRUQifX0sImhlcm9QaWQiOnsic2luZ2xlVmFsdWVBdHRyaWJ1dGUiOnsia2V5IjoiaGVyb1BpZCIsImluZmVyZW5jZVR5cGUiOiJQSUQiLCJ2YWx1ZSI6Ik1PQkhEVkZLU1NIUFVZSEIiLCJ2YWx1ZVR5cGUiOiJTSU5HTEVfVkFMVUVEIn19LCJ0aXRsZSI6eyJtdWx0aVZhbHVlZEF0dHJpYnV0ZSI6eyJrZXkiOiJ0aXRsZSIsImluZmVyZW5jZVR5cGUiOiJUSVRMRSIsInZhbHVlcyI6WyJHYWxheHkgUzI0IDVHIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fX19fQ%3D%3D"

In [6]:
headers={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}

In [12]:
response=requests.get(url,headers=headers)

In [15]:
response.status_code==200

True

In [16]:
print(response)

<Response [200]>

In [17]:
#change 
soup=BeautifulSoup(response.content,'html.parser')
print(soup)

<!DOCTYPE html>
<html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.aa1465.css" rel="stylesheet"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/bundle.fbaef9.css" rel="stylesheet"/><meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="102988293558" property="fb:page_id"/><meta content="658873552,624500995,100000233612389" property="fb:admins"/><link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/><link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/><meta content="website" property="og:type"/><meta content="Flipkart.com" name="og_site_name" property="og:site_name"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/><meta content="app" name="twitter:card"/><meta content="@flipkart" name="twitter:site"/><meta content="@flipkart" name="twitter:creator"/><meta content="Samsung S24 5G SD - Buy Samsung S24 5G SD Online at Low Prices In India | Flipkart.com" name="twitter:title"/><meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/><meta content="in" name="twitter:app:country"/><meta content="Flipkart" name="al:ios:app_name"/><meta content="742044692" name="al:ios:app_store_id"/><meta content="Flipkart" name="twitter:app:name:iphone"/><meta content="742044692" name="twitter:app:id:iphone"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/><meta content="Flipkart" name="twitter:app:name:ipad"/><meta content="742044692" name="twitter:app:id:ipad"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/><meta content="Flipkart" name="twitter:app:name:googleplay"/><meta content="com.flipkart.android" name="twitter:app:id:googleplay"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/><style>#container {
			height: 100%;
		}</style> <script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/runtime.4ec4359d.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/vendor.79dfd802.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_common.3b9e09f1.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app_modules.f883c700.js"></script><script crossorigin="anonymous" defer="defer" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/js/app.9a1ef73e.js"></script> <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.647087.css" rel="stylesheet"/><title>Samsung S24 5G SD - Buy Samsung S24 5G SD Online at Low Prices In India | Flipkart.com</title><meta content="Samsung S24 5G SD - Buy Samsung S24 5G SD Online at Low Prices In India | Flipkart.com" name="og_title" property="og:title"><meta content="Samsung S24 5G SD 4io" name="Keywords"> <meta content="Samsung S24 5G SD - Shop Samsung S24 5G SD Online at Best Prices in India on Flipkart.com. &amp;#10004; Free Shipping &amp;#10004; Cash on Delivery &amp;#10004; Best Offers" name="Description"><meta content="Samsung S24 5G SD - Shop Samsung S24 5G SD Online at Best Prices in India on Flipkart.com. &amp;#10004; Free Shipping &amp;#10004; Cash on Delivery &amp;#10004; Best Offers" property="og:description"> <meta content="noindex" name="robots"> <meta content="https://www.flipkart.com/tyy/4io/~cs-yyz0z07a06/pr?sid=tyy,4io" name="og_url" property="og:url"><meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"> <!--[if IE 9 ]>
	<script nonce="9868374786241580570">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]--><!--[if !IE]><!--><script nonce="9868374786241580570">if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}</script><!--<![endif]--> <script nonce="9868374786241580570">;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};

			;NREUM.loader_config={accountID:"3700282",trustKey:"3679896",agentID:"1588759528",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528"}
			;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-dd5f16cdf95712c6cba",applicationID:"1588759528",sa:1}

			;/*! For license information please see nr-loader-spa-1.236.0.min.js.LICENSE.txt */

In [31]:
parent_class="lvJbLV col-12-12"
print(parent_class)
print(len(parent_class))

lvJbLV col-12-12
16

In [39]:
products=soup.findAll("div",class_="lvJbLV col-12-12")
print(products)
print(len(products))

[<div class="lvJbLV col-12-12"><div class="v360g_"><section class="JPBFuF vRd1kF"><div class="AF1m2F"><div class="UHMz4K"><span>Filters</span></div></div></section><div class="_f7dpA"><section class="EbGpCV"><div class="ejUPwC"><span>CATEGORIES</span></div><div><div class="pBPis1"><span><svg class="QASjE5" height="10" viewbox="0 0 16 27" width="10" xmlns="http://www.w3.org/2000/svg"><path class="zMV6HH" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></span><a class="HJtI4S ECYCDD" href="/mobiles-accessories/pr?sid=tyy&amp;otracker=categorytree" title="Mobiles &amp; Accessories">Mobiles &amp; Accessories</a></div></div><div><div class="pBPis1"><span><svg class="QASjE5" height="10" viewbox="0 0 16 27" width="10" xmlns="http://www.w3.org/2000/svg"><path class="" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></span><a class="GD4sye ECYCDD" href="/mobiles/pr?sid=tyy,4io&amp;otracker=categorytree" title="Mobiles">Mobiles</a></div></div></section></div><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Brand</div><svg class="RlN0VL WInslT" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div><div class="kMXMaw"><div class="Za3X8s"><div class="tx4xZf StZidb" title="Samsung"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">Samsung</div></label></div></div></div></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">RAM</div><svg class="RlN0VL WInslT" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div><div class="kMXMaw"><div class="Za3X8s"><div class="tx4xZf StZidb" title="8 GB and Above"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">8 GB and Above</div></label></div></div></div></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Network Type</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Internal Storage</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Processor Brand</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Type</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Clock Speed</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Operating System</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Battery Capacity</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Speciality</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Resolution Type</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Sim Type</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Screen Size</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Number of Cores</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="XC54e7 vRd1kF"><div class="CdN64s AF1m2F"><div class="WTZOvT UHMz4K"><span>Price</span></div></div><div class="IpKLv3"><div class="TITC61"><div class="oLh4VS" style="height:0;width:0"></div></div></div><div class="idEhJw"><div class="egvN4t"><div class="lPYKVv y2Kgh9"><div class="G12X4V"></div></div><div class="lPYKVv jVLYlZ"><div class="G12X4V"></div></div><div class="Gv4anF"></div><div class="Gv4anF vPxTYU"></div></div><div class="fuJX8f"><div class="gQpOOi" style="width:undefinedpx">.</div><div class="gQpOOi" style="width:undefinedpx">.</div><div class="gQpOOi" style="width:undefinedpx">.</div><div class="gQpOOi" style="width:undefinedpx">.</div><div class="gQpOOi" style="width:undefinedpx">.</div><div class="gQpOOi" style="width:0px">.</div></div></div><div class="MoAPVV"><div class="FrhiFV"><select class="hbnjE2"><option class="Zn9tum" selected="" value="Min">Min</option><option class="Zn9tum" value="10000">₹10000</option><option class="Zn9tum" value="15000">₹15000</option><option class="Zn9tum" value="20000">₹20000</option><option class="Zn9tum" value="30000">₹30000</option></select></div><div class="c0pX5P">to</div><div class="WoGl7t"><select class="hbnjE2"><option class="Zn9tum" value="10000">₹10000</option><option class="Zn9tum" value="15000">₹15000</option><option class="Zn9tum" value="20000">₹20000</option><option class="Zn9tum" value="30000">₹30000</option><option class="Zn9tum" selected="" value="Max">₹30000+</option></select></div></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Discount</div><svg class="RlN0VL WInslT" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div><div class="kMXMaw"><div class="Za3X8s"><div class="tx4xZf StZidb" title="40% or more"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">40% or more</div></label></div></div><div class="tx4xZf StZidb" title="30% or more"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">30% or more</div></label></div></div><div class="tx4xZf StZidb" title="20% or more"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">20% or more</div></label></div></div><div class="tx4xZf StZidb" title="10% or more"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">10% or more</div></label></div></div><div class="tx4xZf StZidb" title="50% or more"><div class="i5kg2N zu805X"><label class="BMOCJ3 XLPYMm StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">50% or more</div></label></div></div></div></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Customer Ratings</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Primary Camera</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="vRd1kF J5IblS"><label class="BMOCJ3 qJewMY"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx PNZDOO"></div><div class="buvtMR"><div class="h69y2R"><img class="h69y2R" height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_9e47c1.png"/></div></div></label><div class="ewLL6y"><span class="question">?</span></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Secondary Camera</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Features</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Offers</div><svg class="RlN0VL WInslT" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div><div class="kMXMaw"><div class="Za3X8s"><div class="tx4xZf StZidb" title="Special Price"><div class="i5kg2N zu805X"><label class="BMOCJ3 StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">Special Price</div></label></div></div><div class="tx4xZf StZidb" title="Buy More, Save More"><div class="i5kg2N zu805X"><label class="BMOCJ3 XLPYMm StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">Buy More, Save More</div></label></div></div><div class="tx4xZf StZidb" title="No Cost EMI"><div class="i5kg2N zu805X"><label class="BMOCJ3 XLPYMm StZidb"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div><div class="buvtMR">No Cost EMI</div></label></div></div></div></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">Availability</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section><section class="KNnSWQ vRd1kF"><div class="iCspr8 AF1m2F"><div class="_6odwB UHMz4K">GST Invoice Available</div><svg class="RlN0VL" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="eMqmVf" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div></section></div></div>, <div class="lvJbLV col-12-12"><a class="X78vzd" href="/buying-guide/mobiles?sid=tyy,4io&amp;otracker=bg_from_browse_lhs" title="Buying Guide"><div><span>Need help?</span></div><div class="cbYM5o"><span>Help me decide</span><svg class="abVqmy" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg"><path class="ChBu7y" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff"></path></svg></div><img alt="Buying Guide" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/buying-guide-illustration_4dd325.png"/></a></div>, <div class="lvJbLV col-12-12"><div class="nZIRY7"><div data-id="MOBHDVFKVGGGHBDX" style="width:100%"><div class="jIjQ8S"><a class="k7wcnx" href="/samsung-galaxy-s24-5g-snapdragon-onyx-black-256-gb/p/itm0eb31619428e4?pid=MOBHDVFKVGGGHBDX&amp;lid=LSTMOBHDVFKVGGGHBDX8KNAAD&amp;marketplace=FLIPKART&amp;store=tyy%2F4io&amp;srno=b_1_1&amp;otracker=browse&amp;fm=organic&amp;iid=en_6lE2SQFk7T0-8oy3mmDg1JOxOUV8UwoFQVZDdETDesFcVco1vMPDPS98JYS1Eple_dNmnPrDtxm1ldbHZRc0R_UFjCTyOHoHZs-Z5_PS_w0%3D&amp;ppt=None&amp;ppn=None&amp;ssid=zy8hdvyfkg0000001770287386802" rel="noopener noreferrer" target="_blank"><div class="T6hTMI"><div class="R7Cntx"><div><div class="lWX0_T" style="height:200px;width:200px"><img alt="Samsung Galaxy S24 5G Snapdragon (Onyx Black, 256 GB)" class="UCc1lI" loading="eager" src="https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/r/8/1/-original-imahfz2tenzpsd3p.jpeg?q=70"/></div></div></div><div class="b0bTm6"><div class="FJ7IAS"><span class="ZhHnSZ"><label class="BMOCJ3"><input class="UXWKAE" readonly="" type="checkbox"/><div class="ybaCDx"></div></label></span><label class="fU6cHR"><span>Add to Compare</span></label></div></div><div class="SJekt1 fM1bsa"><div class="JiknFv"><svg class="rE8OAo" height="16" viewbox="0 0 20 16" width="16" xmlns="http://www.w3.org/2000/svg"><path class="JX9D2X" d="M8.695 16.682C4.06 12.382 1 9.536 1 6.065 1 3.219 3.178 1 5.95 1c1.566 0 3.069.746 4.05 1.915C10.981 1.745 12.484 1 14.05 1 16.822 1 19 3.22 19 6.065c0 3.471-3.06 6.316-7.695 10.617L10 17.897l-1.305-1.215z" fill="#2874F0" fill-rule="evenodd" opacity=".9" stroke="#FFF"></path></svg></div></div></div><div class="ZFwe0M row"><div class="col col-7-12"><div class="t7gRps"><svg class="" height="18" width="62" xmlns="http://www.w3.org/2000/svg"><rect fill="white" height="18" width="62"></rect><path d="M5.82955 6.45455C5.77841 6.02273 5.57102 5.6875 5.20739 5.44886C4.84375 5.21023 4.39773 5.09091 3.86932 5.09091C3.48295 5.09091 3.14489 5.15341 2.85511 5.27841C2.56818 5.40341 2.34375 5.57528 2.18182 5.79403C2.02273 6.01278 1.94318 6.26136 1.94318 6.53977C1.94318 6.77273 1.99858 6.97301 2.10938 7.14062C2.22301 7.3054 2.3679 7.44318 2.54403 7.55398C2.72017 7.66193 2.90483 7.75142 3.09801 7.82244C3.29119 7.89062 3.46875 7.94602 3.63068 7.98864L4.51705 8.22727C4.74432 8.28693 4.99716 8.36932 5.27557 8.47443C5.55682 8.57955 5.82528 8.72301 6.08097 8.90483C6.33949 9.08381 6.55256 9.31392 6.72017 9.59517C6.88778 9.87642 6.97159 10.2216 6.97159 10.6307C6.97159 11.1023 6.84801 11.5284 6.60085 11.9091C6.35653 12.2898 5.99858 12.5923 5.52699 12.8168C5.05824 13.0412 4.48864 13.1534 3.81818 13.1534C3.19318 13.1534 2.65199 13.0526 2.1946 12.8509C1.74006 12.6491 1.3821 12.3679 1.12074 12.0071C0.862216 11.6463 0.715909 11.2273 0.681818 10.75H1.77273C1.80114 11.0795 1.91193 11.3523 2.10511 11.5682C2.30114 11.7812 2.5483 11.9403 2.84659 12.0455C3.14773 12.1477 3.47159 12.1989 3.81818 12.1989C4.22159 12.1989 4.58381 12.1335 4.90483 12.0028C5.22585 11.8693 5.48011 11.6847 5.66761 11.4489C5.85511 11.2102 5.94886 10.9318 5.94886 10.6136C5.94886 10.3239 5.8679 10.0881 5.70597 9.90625C5.54403 9.72443 5.33097 9.5767 5.06676 9.46307C4.80256 9.34943 4.51705 9.25 4.21023 9.16477L3.13636 8.85795C2.45455 8.66193 1.91477 8.3821 1.51705 8.01847C1.11932 7.65483 0.920455 7.17898 0.920455 6.59091C0.920455 6.10227 1.05256 5.67614 1.31676 5.3125C1.58381 4.94602 1.94176 4.66193 2.39062 4.46023C2.84233 4.25568 3.34659 4.15341 3.90341 4.15341C4.46591 4.15341 4.96591 4.25426 5.40341 4.45597C5.84091 4.65483 6.1875 4.92756 6.44318 5.27415C6.7017 5.62074 6.83807 6.0142 6.85227 6.45455H5.82955ZM8.5728 15.4545V6.45455H9.54439V7.49432H9.66371C9.73757 7.38068 9.83984 7.2358 9.97053 7.05966C10.104 6.88068 10.2944 6.72159 10.5415 6.58239C10.7915 6.44034 11.1296 6.36932 11.5558 6.36932C12.1069 6.36932 12.5927 6.5071 13.0131 6.78267C13.4336 7.05824 13.7617 7.44886 13.9975 7.95455C14.2333 8.46023 14.3512 9.05682 14.3512 9.74432C14.3512 10.4375 14.2333 11.0384 13.9975 11.5469C13.7617 12.0526 13.435 12.4446 13.0174 12.723C12.5998 12.9986 12.1183 13.1364 11.5728 13.1364C11.1523 13.1364 10.8157 13.0668 10.5629 12.9276C10.31 12.7855 10.1154 12.625 9.97905 12.446C9.84268 12.2642 9.73757 12.1136 9.66371 11.9943H9.57848V15.4545H8.5728ZM9.56143 9.72727C9.56143 10.2216 9.63388 10.6577 9.77876 11.0355C9.92365 11.4105 10.1353 11.7045 10.4137 11.9176C10.6921 12.1278 11.033 12.233 11.4364 12.233C11.8569 12.233 12.2077 12.1222 12.489 11.9006C12.7731 11.6761 12.9862 11.375 13.1282 10.9972C13.2731 10.6165 13.3455 10.1932 13.3455 9.72727C13.3455 9.26705 13.2745 8.85227 13.1325 8.48295C12.9933 8.1108 12.7816 7.81676 12.4975 7.60085C12.2163 7.3821 11.8626 7.27273 11.4364 7.27273C11.0273 7.27273 10.6836 7.37642 10.4052 7.58381C10.1268 7.78835 9.91655 8.07528 9.7745 8.4446C9.63246 8.81108 9.56143 9.23864 9.56143 9.72727ZM18.5444 13.1364C17.9535 13.1364 17.435 12.9957 16.989 12.7145C16.5458 12.4332 16.1992 12.0398 15.9492 11.5341C15.7021 11.0284 15.5785 10.4375 15.5785 9.76136C15.5785 9.07955 15.7021 8.48437 15.9492 7.97585C16.1992 7.46733 16.5458 7.07244 16.989 6.79119C17.435 6.50994 17.9535 6.36932 18.5444 6.36932C19.1353 6.36932 19.6523 6.50994 20.0955 6.79119C20.5415 7.07244 20.8881 7.46733 21.1353 7.97585C21.3853 8.48437 21.5103 9.07955 21.5103 9.76136C21.5103 10.4375 21.3853 11.0284 21.1353 11.5341C20.8881 12.0398 20.5415 12.4332 20.0955 12.7145C19.6523 12.9957 19.1353 13.1364 18.5444 13.1364ZM18.5444 12.233C18.9933 12.233 19.3626 12.1179 19.6523 11.8878C19.9421 11.6577 20.1566 11.3551 20.2958 10.9801C20.435 10.6051 20.5046 10.1989 20.5046 9.76136C20.5046 9.32386 20.435 8.91619 20.2958 8.53835C20.1566 8.16051 19.9421 7.85511 19.6523 7.62216C19.3626 7.3892 18.9933 7.27273 18.5444 7.27273C18.0955 7.27273 17.7262 7.3892 17.4364 7.62216C17.1467 7.85511 16.9322 8.16051 16.793 8.53835C16.6538 8.91619 16.5842 9.32386 16.5842 9.76136C16.5842 10.1989 16.6538 10.6051 16.793 10.9801C16.9322 11.3551 17.1467 11.6577 17.4364 11.8878C17.7262 12.1179 18.0955 12.233 18.5444 12.233ZM24.0511 9.0625V13H23.0455V6.45455H24.017V7.47727H24.1023C24.2557 7.14489 24.4886 6.87784 24.8011 6.67614C25.1136 6.47159 25.517 6.36932 26.0114 6.36932C26.4545 6.36932 26.8423 6.46023 27.1747 6.64205C27.5071 6.82102 27.7656 7.09375 27.9503 7.46023C28.1349 7.82386 28.2273 8.28409 28.2273 8.84091V13H27.2216V8.90909C27.2216 8.39489 27.0881 7.99432 26.821 7.70739C26.554 7.41761 26.1875 7.27273 25.7216 7.27273C25.4006 7.27273 25.1136 7.34233 24.8608 7.48153C24.6108 7.62074 24.4134 7.82386 24.2685 8.09091C

C:\Users\hp\AppData\Local\Temp\ipykernel_10192\2165052653.py:1: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  products=soup.findAll("div",class_="lvJbLV col-12-12")

In [64]:
df = pd.DataFrame()
name_list = []
price_list = []

In [65]:

for product in products:
    name=product.find("div",class_="RG5Slk")
    price=product.find("div",class_="hZ3P6w DeU9vF")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list.append(price)
        name_list.append(name)
df["Name"]=name_list
df["Price"]=price_list
df

                                                Name    Price
0  Samsung Galaxy S24 5G Snapdragon (Onyx Black, ...  ₹47,999
1  Samsung Galaxy S24 5G Snapdragon (Onyx Black, ...  ₹42,999
2  Samsung Galaxy S24 5G Snapdragon (Marble Gray,...  ₹47,999
3  Samsung Galaxy S24 5G Snapdragon (Amber Yellow...  ₹42,999
4  Samsung Galaxy S24 5G Snapdragon (Amber Yellow...  ₹47,999
5  Samsung Galaxy S24 5G Snapdragon (Cobalt Viole...  ₹42,999
6  Samsung Galaxy S24 5G Snapdragon (Cobalt Viole...  ₹47,999

In [115]:
url2="https://books.toscrape.com/"

In [116]:
header2 = { 
    "User-Agent":
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}

In [117]:
responsed=requests.get(url2,headers=header2)

In [118]:
responsed.status_code==200

True

In [119]:
print(responsed)

<Response [200]>

In [120]:
soup2=BeautifulSoup(responsed.content,'html.parser')
print(soup2)

<!DOCTYPE html>

<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-us"> <!--<![endif]-->
<head>
<title>
    All products | Books to Scrape - Sandbox
</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="24th Jun 2016 09:29" name="created"/>
<meta content="" name="description"/>
<meta content="width=device-width" name="viewport"/>
<meta content="NOARCHIVE,NOCACHE" name="robots"/>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="static/oscar/favicon.ico" rel="shortcut icon"/>
<link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
<link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
</head>
<body class="default" id="default">
<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>
<div class="container-fluid page">
<div class="page_inner">
<ul class="breadcrumb">
<li>
<a href="index.html">Home</a>
</li>
<li class="active">All products</li>
</ul>
<div class="row">
<aside class="sidebar col-sm-4 col-md-3">
<div id="promotions_left">
</div>
<div class="side_categories">
<ul class="nav nav-list">
<li>
<a href="catalogue/category/books_1/index.html">

                                Books

                        </a>
<ul>
<li>
<a href="catalogue/category/books/travel_2/index.html">

                                Travel

                        </a>
</li>
<li>
<a href="catalogue/category/books/mystery_3/index.html">

                                Mystery

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/classics_6/index.html">

                                Classics

                        </a>
</li>
<li>
<a href="catalogue/category/books/philosophy_7/index.html">

                                Philosophy

                        </a>
</li>
<li>
<a href="catalogue/category/books/romance_8/index.html">

                                Romance

                        </a>
</li>
<li>
<a href="catalogue/category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/fiction_10/index.html">

                                Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/childrens_11/index.html">

                                Childrens

                        </a>
</li>
<li>
<a href="catalogue/category/books/religion_12/index.html">

                                Religion

                        </a>
</li>
<li>
<a href="catalogue/category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/music_14/index.html">

                                Music

                        </a>
</li>
<li>
<a href="catalogue/category/books/default_15/index.html">

                                Default

                        </a>
</li>
<li>
<a href="catalogue/category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>
</li>
<li>
<a href="catalogue/category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>
</li>
<li>
<a href="catalogue/category/books/fantasy_19/index.html">

                                Fantasy

                        </a>
</li>
<li>
<a href="catalogue/category/books/new-adult_20/index.html">

                                New Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/young-adult_21/index.html">

                                Young Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/science_22/index.html">

                                Science

                        </a>
</li>
<li>
<a href="catalogue/category/books/poetry_23/index.html">

                                Poetry

                        </a>
</li>
<li>
<a href="catalogue/category/books/paranormal_24/index.html">

                                Paranormal

                        </a>
</li>
<li>
<a href="catalogue/category/books/art_25/index.html">

                                Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/psychology_26/index.html">

                                Psychology

                        </a>
</li>
<li>
<a href="catalogue/category/books/autobiography_27/index.html">

                                Autobiography

                        </a>
</li>
<li>
<a href="catalogue/category/books/parenting_28/index.html">

                                Parenting

                        </a>
</li>
<li>
<a href="catalogue/category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/humor_30/index.html">

                                Humor

                        </a>
</li>
<li>
<a href="catalogue/category/books/horror_31/index.html">

                                Horror

                        </a>
</li>
<li>
<a href="catalogue/category/books/history_32/index.html">

                                History

                        </a>
</li>
<li>
<a href="catalogue/category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/business_35/index.html">

                                Business

                        </a>
</li>
<li>
<a href="catalogue/category/books/biography_36/index.html">

                                Biography

                        </a>
</li>
<li>
<a href="catalogue/category/books/thriller_37/index.html">

                                Thriller

                        </a>
</li>
<li>
<a href="catalogue/category/books/contemporary_38/index.html">

                                Contemporary

                        </a>
</li>
<li>
<a href="catalogue/category/books/spirituality_39/index.html">

                                Spirituality

                        </a>
</li>
<li>
<a href="catalogue/category/books/academic_40/index.html">

                                Academic

                        </a>
</li>
<li>
<a href="catalogue/category/books/self-help_41/index.html">

                                Self Help

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical_42/index.html">

                                Historical

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian_43/index.html">

                                Christian

                        </a>
</li>
<li>
<a href="catalogue/category/books/suspense_44/index.html">

                                Suspense

                        </a>
</li>
<li>
<a href="catalogue/category/books/short-stories_45/index.html">

                                Short Stories

                        </a>
</li>
<li>
<a href="catalogue/category/books/novels_46/index.html">

                                Novels

                        </a>
</li>
<li>
<a href="catalogue/category/books/health_47/index.html">

                                Health

                        </a>
</li>
<li>
<a href="catalogue/category/books/politics_48/index.html">

                                Politics

                        </a>
</li>
<li>
<a href="catalogue/category/books/cultural_49/index.html">

                                Cultural

                        </a>
</li>
<li>
<a href="catalogue/category/books/erotica_50/index.html">

                                Erotica

                        </a>
</li>
<li>
<a href="catalogue/category/books/crime_51/index.html">

                                Crime

                        </a>
</li>
</ul></li>
</ul>
</div>
</aside>
<div class="col-sm-8 col-md-9">
<div class="page-header action">
<h1>All products</h1>
</div>
<div id="messages">
</div>
<div id="promotions">
</div>
<form class="form-horizontal" method="get">
<div style="display:none">
</div>
<strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>
<section>
<div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
<div>
<ol class="row">
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">

In [121]:
parent_class2="col-xs-6 col-sm-4 col-md-3 col-lg-3"
print(parent_class2)
print(len(parent_class2))

col-xs-6 col-sm-4 col-md-3 col-lg-3
35

In [122]:
products2=soup2.find_all("li",class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")
print(products2)
print(len(products2))

[<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
<div class="product_price">
<p class="price_color">£20.66</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
<div class="product_price">
<p class="price_color">£17.46</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
<div class="product_price">
<p class="price_color">£52.29</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
<div class="product_price">
<p class="price_color">£35.02</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
<div class="product_price">
<p class="price_color">£57.25</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
<div class="product_price">
<p class="price_color">£23.88</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
<div class="product_price">
<p class="price_color">£37.59</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
<div class="product_price">
<p class="price_color">£51.33</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>, <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
<div class="product_price">
<p class="price_color">£45.17</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>]
20

In [123]:
df2 = pd.DataFrame()
name_list2 = []
price_list2 = []

In [124]:

for product in products2:
    name=product.find("h3").find("a")
    price=product.find("p",class_="price_color")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list2.append(price)
        name_list2.append(name)
df2["Name"]=name_list2
df2["Price"]=price_list2
df2

                                     Name   Price
0                      A Light in the ...  £51.77
1                      Tipping the Velvet  £53.74
2                              Soumission  £50.10
3                           Sharp Objects  £47.82
4            Sapiens: A Brief History ...  £54.23
5                         The Requiem Red  £22.65
6            The Dirty Little Secrets ...  £33.34
7                 The Coming Woman: A ...  £17.93
8                     The Boys in the ...  £22.60
9                         The Black Maria  £52.15
10  Starving Hearts (Triangular Trade ...  £13.99
11                  Shakespeare's Sonnets  £20.66
12                            Set Me Free  £17.46
13    Scott Pilgrim's Precious Little ...  £52.29
14                      Rip it Up and ...  £35.02
15                  Our Band Could Be ...  £57.25
16                                   Olio  £23.88
17        Mesaerion: The Best Science ...  £37.59
18           Libertarianism for Beginners  £51.33
19                It's Only the Himalayas  £45.17

In [125]:
url3="https://www.zomato.com/chandigarh/restaurants"

In [126]:
header3={
    "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}

In [127]:
rresponse3=requests.get(url2,headers=header3)
print(rresponse3)
rresponse3.status_code==200

<Response [200]>

True

In [128]:
products3=soup.find_all("div",class_="sc-evWYkj cRThYq")
print(products3)
print(len(products3))

[]
0

In [129]:
soup3=BeautifulSoup(rresponse3.content,'html.parser')
print(soup3)

<!DOCTYPE html>

<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-us"> <!--<![endif]-->
<head>
<title>
    All products | Books to Scrape - Sandbox
</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="24th Jun 2016 09:29" name="created"/>
<meta content="" name="description"/>
<meta content="width=device-width" name="viewport"/>
<meta content="NOARCHIVE,NOCACHE" name="robots"/>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="static/oscar/favicon.ico" rel="shortcut icon"/>
<link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
<link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
</head>
<body class="default" id="default">
<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>
<div class="container-fluid page">
<div class="page_inner">
<ul class="breadcrumb">
<li>
<a href="index.html">Home</a>
</li>
<li class="active">All products</li>
</ul>
<div class="row">
<aside class="sidebar col-sm-4 col-md-3">
<div id="promotions_left">
</div>
<div class="side_categories">
<ul class="nav nav-list">
<li>
<a href="catalogue/category/books_1/index.html">

                                Books

                        </a>
<ul>
<li>
<a href="catalogue/category/books/travel_2/index.html">

                                Travel

                        </a>
</li>
<li>
<a href="catalogue/category/books/mystery_3/index.html">

                                Mystery

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/classics_6/index.html">

                                Classics

                        </a>
</li>
<li>
<a href="catalogue/category/books/philosophy_7/index.html">

                                Philosophy

                        </a>
</li>
<li>
<a href="catalogue/category/books/romance_8/index.html">

                                Romance

                        </a>
</li>
<li>
<a href="catalogue/category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/fiction_10/index.html">

                                Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/childrens_11/index.html">

                                Childrens

                        </a>
</li>
<li>
<a href="catalogue/category/books/religion_12/index.html">

                                Religion

                        </a>
</li>
<li>
<a href="catalogue/category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/music_14/index.html">

                                Music

                        </a>
</li>
<li>
<a href="catalogue/category/books/default_15/index.html">

                                Default

                        </a>
</li>
<li>
<a href="catalogue/category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>
</li>
<li>
<a href="catalogue/category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>
</li>
<li>
<a href="catalogue/category/books/fantasy_19/index.html">

                                Fantasy

                        </a>
</li>
<li>
<a href="catalogue/category/books/new-adult_20/index.html">

                                New Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/young-adult_21/index.html">

                                Young Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/science_22/index.html">

                                Science

                        </a>
</li>
<li>
<a href="catalogue/category/books/poetry_23/index.html">

                                Poetry

                        </a>
</li>
<li>
<a href="catalogue/category/books/paranormal_24/index.html">

                                Paranormal

                        </a>
</li>
<li>
<a href="catalogue/category/books/art_25/index.html">

                                Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/psychology_26/index.html">

                                Psychology

                        </a>
</li>
<li>
<a href="catalogue/category/books/autobiography_27/index.html">

                                Autobiography

                        </a>
</li>
<li>
<a href="catalogue/category/books/parenting_28/index.html">

                                Parenting

                        </a>
</li>
<li>
<a href="catalogue/category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/humor_30/index.html">

                                Humor

                        </a>
</li>
<li>
<a href="catalogue/category/books/horror_31/index.html">

                                Horror

                        </a>
</li>
<li>
<a href="catalogue/category/books/history_32/index.html">

                                History

                        </a>
</li>
<li>
<a href="catalogue/category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/business_35/index.html">

                                Business

                        </a>
</li>
<li>
<a href="catalogue/category/books/biography_36/index.html">

                                Biography

                        </a>
</li>
<li>
<a href="catalogue/category/books/thriller_37/index.html">

                                Thriller

                        </a>
</li>
<li>
<a href="catalogue/category/books/contemporary_38/index.html">

                                Contemporary

                        </a>
</li>
<li>
<a href="catalogue/category/books/spirituality_39/index.html">

                                Spirituality

                        </a>
</li>
<li>
<a href="catalogue/category/books/academic_40/index.html">

                                Academic

                        </a>
</li>
<li>
<a href="catalogue/category/books/self-help_41/index.html">

                                Self Help

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical_42/index.html">

                                Historical

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian_43/index.html">

                                Christian

                        </a>
</li>
<li>
<a href="catalogue/category/books/suspense_44/index.html">

                                Suspense

                        </a>
</li>
<li>
<a href="catalogue/category/books/short-stories_45/index.html">

                                Short Stories

                        </a>
</li>
<li>
<a href="catalogue/category/books/novels_46/index.html">

                                Novels

                        </a>
</li>
<li>
<a href="catalogue/category/books/health_47/index.html">

                                Health

                        </a>
</li>
<li>
<a href="catalogue/category/books/politics_48/index.html">

                                Politics

                        </a>
</li>
<li>
<a href="catalogue/category/books/cultural_49/index.html">

                                Cultural

                        </a>
</li>
<li>
<a href="catalogue/category/books/erotica_50/index.html">

                                Erotica

                        </a>
</li>
<li>
<a href="catalogue/category/books/crime_51/index.html">

                                Crime

                        </a>
</li>
</ul></li>
</ul>
</div>
</aside>
<div class="col-sm-8 col-md-9">
<div class="page-header action">
<h1>All products</h1>
</div>
<div id="messages">
</div>
<div id="promotions">
</div>
<form class="form-horizontal" method="get">
<div style="display:none">
</div>
<strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>
<section>
<div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
<div>
<ol class="row">
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
<div class="product_price">
<p class="price_color">£53.74</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
<div class="product_price">
<p class="price_color">£50.10</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
<div class="product_price">
<p class="price_color">£47.82</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
</div>
<p class="star-rating Five">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
<div class="product_price">
<p class="price_color">£54.23</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
<div class="product_price">
<p class="price_color">£22.65</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
<div class="product_price">
<p class="price_color">£33.34</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
<div class="product_price">
<p class="price_color">£17.93</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
</div>
<p class="star-rating Four">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
<div class="product_price">
<p class="price_color">£22.60</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
</div>
<p class="star-rating One">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
<div class="product_price">
<p class="price_color">£52.15</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">
<div class="image_container">
<a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
</div>
<p class="star-rating Two">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
<div class="product_price">
<p class="price_color">£13.99</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>
</li>
<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
<article class="product_pod">

In [130]:
df3 = pd.DataFrame()
name_list3 = []
price_list3= []

In [131]:
for product in products3:
    name=product.find("h4",class_="sc-1hp8d8a-0 sc-Ehqfj bxOQva")
    price=product.find("p",class_="sc-1hez2tp-0 sc-gggouf KXcjT")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list3.append(price)
        name_list3.append(name)
df3["Name"]=name_list3
df3["Price"]=price_list3
df3

Empty DataFrame
Columns: [Name, Price]
Index: []

In [3]:
url4="https://www.swiggy.com/collections/80382?collection_id=80382&tags=layout_CCS_CholeBhature&type=rcv2"
header4={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}
response4=requests.get(url4,headers=header4)
print(response4)
response4.status_code==200
print(response4)
soup4=BeautifulSoup(response4.content,'html.parser')
print(soup4)
parent_class4="sc-beIvYv gpUGEh"
print(parent_class4)
print(len(parent_class4))
products4=soup4.find_all("div",class_="sc-beIvYv gpUGEh")
print(products4)
print(len(products4))
df4 = pd.DataFrame()
name_list4 = []
price_list4 = []

for product in products4:
    name=product.find("div",class_="sc-aXZVg brETgz")
    price=product.find("div",class_="sc-aXZVg OyTrl")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list4.append(price)
        name_list4.append(name)
df4["Name"]=name_list4
df4["Price"]=price_list4
df4

<Response [200]>
<Response [200]>
<!DOCTYPE html>
<html class="" lang="en"><head> <link crossorigin="anonymous" href="https://analytics.swiggy.com" rel="preconnect"/> <link crossorigin="anonymous" href="https://media-assets.swiggy.com" rel="preconnect"/> <link crossorigin="anonymous" href="https://b67f7794189c.edge.sdk.awswaf.com" rel="preconnect"/> <link href="https://media-assets.swiggy.com" rel="dns-prefetch"/> <link href="https://analytics.swiggy.com" rel="dns-prefetch"/> <link href="https://www.googletagmanager.com" rel="dns-prefetch"/> <link href="https://www.gstatic.com" rel="dns-prefetch"/> <link href="https://www.google-analytics.com" rel="dns-prefetch"/> <link href="https://q.quora.com" rel="dns-prefetch"/> <link href="https://www.google.co.in" rel="dns-prefetch"/> <link href="https://www.facebook.com" rel="dns-prefetch"/> <link href="https://www.googleadservices.com" rel="dns-prefetch"/> <link href="https://bat.bing.com" rel="dns-prefetch"/> <meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta charset="utf-8"/> <link crossorigin="anonymous" href="" rel="stylesheet"/> <link as="script" crossorigin="anonymous" href="https://media-assets.swiggy.com/dweb/js/manifest.303754efae2b6d5.js" rel="preload"/> <link as="script" crossorigin="anonymous" href="https://media-assets.swiggy.com/dweb/js/vendor.303754efae2b6d5.js" rel="preload"/> <link as="script" crossorigin="anonymous" href="https://media-assets.swiggy.com/dweb/js/app.303754efae2b6d5.js" rel="preload"/> <link as="font" crossorigin="anonymous" href="https://media-assets.swiggy.com/dls-web-assets/dls/fonts/Gilroy-ExtraBold.woff2" rel="preload" type="font/woff2"/> <link as="font" crossorigin="anonymous" href="https://media-assets.swiggy.com/dls-web-assets/dls/fonts/Gilroy-Bold.woff2" rel="preload" type="font/woff2"/> <link as="font" crossorigin="anonymous" href="https://media-assets.swiggy.com/dls-web-assets/dls/fonts/Gilroy-Medium.woff2" rel="preload" type="font/woff2"/> <link as="font" crossorigin="anonymous" href="https://media-assets.swiggy.com/dls-web-assets/dls/fonts/Gilroy-SemiBold.woff2" rel="preload" type="font/woff2"/> <title>Order Food Online from India's Best Food Delivery Service | Swiggy</title><meta content="Order food online from restaurants and get it delivered. Serving in Bangalore, Hyderabad, Delhi and more. Order Pizzas, Biryanis, from Swiggy." name="description"/><meta content="Food delivery, Online food order, Online food dleivery" name="keywords"/><meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible"/> <meta content="index, follow" name="robots"/> <meta content="Swiggy.com" name="og_site_name" property="og:site_name"/><meta content="Order Food Online from India's Best Food Delivery Service | Swiggy" name="og_title" property="og:title"/><meta content="website" property="og:type"/><meta content="Order food online from restaurants and get it delivered. Serving in Bangalore, Hyderabad, Delhi and more. Order Pizzas, Biryanis, from Swiggy." property="og:description"/> <meta content="https://www.swiggy.com/collections/80382" name="og_url" property="og:url"/> <meta content="https://media-assets.swiggy.com/swiggy/image/upload/c_scale,w_715/portal/m/brand_logos/Swiggy_OG.png" property="og:image"/> <link href="https://media-assets.swiggy.com/portal/m/logo_192x192.png" rel="icon" sizes="192x192"/><link href="https://media-assets.swiggy.com/portal/m/logo_192x192.png" rel="apple-touch-icon" sizes="192x192"/><meta content="#e46d47" name="msapplication-TileColor"/><meta content="https://media-assets.swiggy.com/fl_lossy,f_auto,q_auto,w_150,h_150/portal/m/logo_192x192.png" name="msapplication-TileImage"/><link href="https://media-assets.swiggy.com/portal/m/logo_16x16.ico" rel="icon" type="image/x-icon"/><link href="https://media-assets.swiggy.com/portal/m/logo_32x32.ico" rel="shortcut icon" type="image/x-icon"/><link href="https://media-assets.swiggy.com/fl_lossy,f_auto,q_auto,w_96,h_96/portal/m/logo_192x192.png" rel="icon" type="image/png"/><link href="https://media-assets.swiggy.com/fl_lossy,f_auto,q_auto,w_72,h_72/portal/m/logo_192x192.png" rel="apple-touch-icon-precomposed" sizes="72x72"/><script>"undefined"==typeof Promise&&document.write("<script src=\"https://media-assets.swiggy.com/dweb/libs/es6-promise.js\" defer><\/script>")</script> <script>!function(e,t,a,g,n){e[g]=e[g]||[],e[g].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});var m=t.getElementsByTagName(a)[0],r=t.createElement(a);r.async=!0,r.src="https://www.googletagmanager.com/gtm.js?id=GTM-MJV7Q8Q",m.parentNode.insertBefore(r,m)}(window,document,"script","dataLayer")</script> <script type="application/ld+json">{
        "@context": "http://schema.org",
        "@type": "WebSite",
        "name": "Swiggy",
        "url": "https://www.swiggy.com"
    }</script><script type="application/ld+json">{
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "Swiggy",
        "description": "Order Food Online from India's Best Food Delivery Service | Swiggy",
        "email": "support@swiggy.in",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Bengaluru",
            "addressRegion": "Karnataka",
            "postalCode": "560103",
            "streetAddress": "Swiggy Limited, No. 55 Sy No 8 to 14, I and J Block, 2nd Floor, Embassy Tech Village, Outer Ring Road, Devarbisanahalli, Varthur"
        },
        "url": "https://www.swiggy.com/",
        "logo": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_800,h_800/portal/m/logo_192x192.png",
        "sameAs": [
            "https://www.facebook.com/swiggy.in",
            "https://www.twitter.com/swiggy",
            "https://www.instagram.com/swiggyindia",
            "https://en.wikipedia.org/wiki/Swiggy",
            "https://www.linkedin.com/company/swiggy-in"
        ]

Empty DataFrame
Columns: [Name, Price]
Index: []

In [ ]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
url5="https://www.makemytrip.com/hotels/hotel-listing/?checkin=03012026&city=CTBLR&checkout=03032026&roomStayQualifier=1e0e&locusId=CTBLR&country=IN&locusType=city&searchText=Bengaluru&regionNearByExp=3&rsc=1e1e0e"
header5={
    "user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}
response5=requests.get(url5,headers=header5)
print(response5)
response5.status_code==200
print(response5)
soup5=BeautifulSoup(response5.content,'html.parser')
print(soup5)
parent_class5="listingRow listingRowPerNew bdrPerNew"
print(parent_class5)
print(len(parent_class5))
products5=soup5.find_all("div",class_="listingRow listingRowPerNew bdrPerNew")
print(products5)
print(len(products5))
df5 = pd.DataFrame()
name_list5 = []
price_list5 = []

for product in products5:
    name=product.find("p",class_="latoBlack blackText font20")
    price=product.find("p",class_="priceText latoBlack font22 blackText appendBottom5")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list5.append(price)
        name_list5.append(name)
df5["Name"]=name_list5
df5["Price"]=price_list5
df5

In [12]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
url6="https://www.flipkart.com/all/~cs-7847646c0fa813bb0b1d71a25db94e79/pr?sid=0pm,fcn,821,a7x,2si&marketplace=FLIPKART&restrictLocale=true"
header6={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}
response6=requests.get(url6,headers=header6)
# print(response6)
response6.status_code==200
# print(response6)
soup6=BeautifulSoup(response6.content,'html.parser')
# print(soup6)
parent_class6="RGLWAk"
print(parent_class6)
# print(len(parent_class6))
products6=soup6.find_all("div",class_="RGLWAk")
# print(products6)
print(len(products6))
df6 = pd.DataFrame()
name_list6 = []
price_list6 = []

for product in products6:
    name=product.find("a",class_="pIpigb")
    price=product.find("div",class_="hZ3P6w")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list6.append(price)
        name_list6.append(name)
df6["Name"]=name_list6
df6["Price"]=price_list6
df6

RGLWAk
40

                                                 Name   Price
0   boAt Airdopes 161, Adv 4Mic ENx, 50H Battery,F...    ₹799
1   TRIGGR Kraken X4 with 13mm Drivers, 40ms Laten...    ₹799
2   boAt Airdopes 71,40 H Battery, ENx Tech, Low L...    ₹799
3             BULLSTORM BS ultrapood Bluetooth Gaming    ₹298
4   TECHIO Black Earbuds | True Wireless Stereo | ...    ₹247
5   GOBOULT Z40 with ENC Mic, 60Hr Battery, Metal ...    ₹999
6   myxes New Edition TWS M19 Gaming Earbuds Bluet...    ₹373
7   Sagaft X589 Advanced TWS Earbuds with Hi-Fi So...    ₹693
8   Caidea TW500 Tube Upto 50H Playtime*, ENC, Fas...    ₹399
9   OnePlus Nord Buds 3r TWS Earbud, 10min charge ...  ₹1,799
10  boAt Airdopes 161/163,ASAP Charge,40 H Battery...    ₹799
11  boAt Airdopes 212,Translucent Lid, 50H Battery...    ₹799
12  NS WORLD Thunder Pods | High Bass | Large Batt...    ₹298
13  GWALBROS New White Bluetooth Earbuds, True Wir...    ₹251
14  Caidea TW301 Blogger Upto 40H Playtime*,ENC,Du...    ₹294
15  Stybits X406 Gaming Mode TWS Earbuds with Low ...    ₹699
16  Aroma NB121 Pods Upto 40 Hours Playtime* Type ...    ₹289
17  Portronics Twins S16 in Ear Earbuds With Mic,2...    ₹699
18        Clubics M19: Compact Earbud Bliss Bluetooth    ₹370
19  Aroma NB126 Aster V5.4 Upto 50Hr Playtime* 45M...    ₹499
20  Portronics Harmonics Twins S3 Smart TWS Earbud...    ₹648
21  Caidea TW301 Blogger Upto 40H Playtime*,ENC,Du...    ₹294
22  Yildiz Buds Wireless 5 with 50dB ANC,360 degre...    ₹431
23  NEXX ARHAM TWS BLUETOOTH HEADSET WIRELESS TWIN...    ₹298
24  GOBOULT Astra with Quad Mic ENC, 48Hrs Battery...  ₹1,099
25  Earboss 4 Mics Auto AI ENC , 120 HRS Playback ...    ₹448
26  HOPPUP Predator Xo3 Gaming Earbuds with 35MS B...    ₹797
27  HOPPUP AirDoze S40 Earbuds with 13MM Drivers, ...    ₹599
28  PHILIPS TAN1150BK Neckband, 60H Playtime, 13mm...    ₹849
29  TECHBROS New Edition TWS M19 PRO with Power Ba...    ₹373
30  Mivi Duopods B1 (Just Launched)45Hrs Playtime,...    ₹799
31  truke BTG Ultra with 60H Playtime, 360Spatial,...    ₹899
32  Aroma NB126 Blaze 32dB Active Noise Cancellati...    ₹499
33  IMMUTABLE Neest SH-12 Wireless Headphones Adju...    ₹601
34  HOPPUP Xo6 Gaming Earbuds with 35MS Low Latenc...    ₹799
35  Hectic Black Earbuds With Premium Quality Soun...    ₹262
36  SIGNATIZE Wireless Neckband Earphones with 10m...    ₹249
37  TRIGGR Kraken X1 with Battery Display, 40ms La...    ₹799
38  myxes Earbuds Bluetooth V5.1 True Wireless ste...    ₹364
39  ZEBRONICS Zeb-Sound Bomb 7, TWS, 60h Backup, B...    ₹799

In [11]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
url7="https://pharmeasy.in/health-care/sports-nutrition-12931"
header7={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}
response7=requests.get(url7,headers=header6)
# print(response6)
response7.status_code==200
# print(response6)
soup7=BeautifulSoup(response7.content,'html.parser')
# print(soup6)
parent_class7="ProductCard_productCard__ftHIX"
print(parent_class6)
# print(len(parent_class6))
products7=soup7.find_all("div",class_="ProductCard_productCard__ftHIX")
# print(products6)
print(len(products7))
df7 = pd.DataFrame()
name_list7 = []
price_list7 = []

for product in products7:
    name=product.find("div",class_="ProductCard_productName__nWQ3x")
    price=product.find("div",class_="ProductCard_priceContainer__99QdN ProductCard_otcListingPriceContainer__PXAT_")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list7.append(price)
        name_list7.append(name)
df7["Name"]=name_list7
df7["Price"]=price_list7
df7

RGLWAk
20

                                           Name                  Price
0   Optimum Nutrition (On) Gold Standard 100...   ₹3611.65MRP ₹4249.00
1   Pharmeasy Daily Protein For Strong Bones...     ₹311.98MRP ₹799.96
2   Muscleblaze Beginner'S Whey Protein | Fa...   ₹1465.46MRP ₹1559.00
3   Nutrabay Gold 100% Whey Protein Isolate ...  ₹5609.49MRP ₹10999.00
4   Isopure Zero Carb Protein - 2.20 Lbs | 1...   ₹5651.55MRP ₹5949.00
5   Pharmeasy Diabetic Protein Powder French...    ₹743.66MRP ₹1957.00
6   Pharmeasy Diabetic Protein Powder French...     ₹355.60MRP ₹889.00
7   Oziva Protein & Herbs For Women Vanilla ...   ₹1531.63MRP ₹1579.00
8   Pharmeasy Diabetic Protein Powder Chocol...     ₹364.49MRP ₹889.00
9   Nutrabay Gold Tri-Blend Whey Protein Str...   ₹2225.47MRP ₹4199.00
10  Optimum Nutrition (On) Gold Standard 100...   ₹1931.16MRP ₹2299.00
11             On Creatine Monohydrate 100g Ind     ₹489.30MRP ₹699.00
12  Optimum Nutrition (On) Performance Whey ...   ₹2931.65MRP ₹3449.00
13  Oziva Protein & Herbs For Men Chocolate ...   ₹1515.84MRP ₹1579.00
14  Muscleblaze Raw Whey Protein Concentrate...           MRP ₹2319.00
15  Optimum Nutrition (On) Gold Standard 100...   ₹7811.16MRP ₹9299.00
16  Optimum Nutrition (On) Gold Standard 100...     ₹755.16MRP ₹899.00
17     On India Micronized Creatine Powder 250g    ₹893.00MRP ₹1175.00
18  Inlife Whey Protein Isolate Concentrate ...           MRP ₹1219.00
19  Inlife Slimming Noni Juice Concentrate W...    ₹895.17MRP ₹1689.00

In [10]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
url7="https://pharmeasy.in/health-care/sports-nutrition-12931"
header7={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}
response7=requests.get(url7,headers=header6)
# print(response6)
response7.status_code==200
# print(response6)
soup7=BeautifulSoup(response7.content,'html.parser')
# print(soup6)
parent_class7="ProductCard_productCard__ftHIX"
print(parent_class6)
# print(len(parent_class6))
products7=soup7.find_all("div",class_="ProductCard_productCard__ftHIX")
# print(products6)
print(len(products7))
df7 = pd.DataFrame()
name_list7 = []
price_list7 = []

for product in products7:
    name=product.find("div",class_="ProductCard_productName__nWQ3x")
    price=product.find("div",class_="ProductCard_priceContainer__99QdN ProductCard_otcListingPriceContainer__PXAT_")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list7.append(price)
        name_list7.append(name)
df7["Name"]=name_list7
df7["Price"]=price_list7
df7

NameError: name 'header6' is not defined

In [11]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
url7="https://puirf.codroidhub.com/api/api/v1/instruments/user/getHomeFacilities"
header7={
    "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"
}

response7 = requests.get(url7,headers=header7)
print(response7)
df7 = pd.DataFrame()
name_list7 = []
price_list7 = []

for product in products7:
    name=product.find("div",class_="ProductCard_productName__nWQ3x")
    price=product.find("div",class_="ProductCard_priceContainer__99QdN ProductCard_otcListingPriceContainer__PXAT_")
    if name!=None:
        name=name.get_text()
    if price!=None:
        price=price.get_text()

    if (price!=None) and (name!=None):
        price_list7.append(price)
        name_list7.append(name)
df7["Name"]=name_list7
df7["Price"]=price_list7
df7

<Response [200]>

NameError: name 'products7' is not defined